# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /app

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /app

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /app/CMakeFiles /app//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /app/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mate-paint

# Build rule for target.
mate-paint: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mate-paint
.PHONY : mate-paint

# fast build rule for target.
mate-paint/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/build
.PHONY : mate-paint/fast

src/clipboard.o: src/clipboard.c.o
.PHONY : src/clipboard.o

# target to build an object file
src/clipboard.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/clipboard.c.o
.PHONY : src/clipboard.c.o

src/clipboard.i: src/clipboard.c.i
.PHONY : src/clipboard.i

# target to preprocess a source file
src/clipboard.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/clipboard.c.i
.PHONY : src/clipboard.c.i

src/clipboard.s: src/clipboard.c.s
.PHONY : src/clipboard.s

# target to generate assembly for a file
src/clipboard.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/clipboard.c.s
.PHONY : src/clipboard.c.s

src/color-picker.o: src/color-picker.c.o
.PHONY : src/color-picker.o

# target to build an object file
src/color-picker.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/color-picker.c.o
.PHONY : src/color-picker.c.o

src/color-picker.i: src/color-picker.c.i
.PHONY : src/color-picker.i

# target to preprocess a source file
src/color-picker.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/color-picker.c.i
.PHONY : src/color-picker.c.i

src/color-picker.s: src/color-picker.c.s
.PHONY : src/color-picker.s

# target to generate assembly for a file
src/color-picker.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/color-picker.c.s
.PHONY : src/color-picker.c.s

src/color.o: src/color.c.o
.PHONY : src/color.o

# target to build an object file
src/color.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/color.c.o
.PHONY : src/color.c.o

src/color.i: src/color.c.i
.PHONY : src/color.i

# target to preprocess a source file
src/color.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/color.c.i
.PHONY : src/color.c.i

src/color.s: src/color.c.s
.PHONY : src/color.s

# target to generate assembly for a file
src/color.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/color.c.s
.PHONY : src/color.c.s

src/cv_airbrush_tool.o: src/cv_airbrush_tool.c.o
.PHONY : src/cv_airbrush_tool.o

# target to build an object file
src/cv_airbrush_tool.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/cv_airbrush_tool.c.o
.PHONY : src/cv_airbrush_tool.c.o

src/cv_airbrush_tool.i: src/cv_airbrush_tool.c.i
.PHONY : src/cv_airbrush_tool.i

# target to preprocess a source file
src/cv_airbrush_tool.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/cv_airbrush_tool.c.i
.PHONY : src/cv_airbrush_tool.c.i

src/cv_airbrush_tool.s: src/cv_airbrush_tool.c.s
.PHONY : src/cv_airbrush_tool.s

# target to generate assembly for a file
src/cv_airbrush_tool.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/cv_airbrush_tool.c.s
.PHONY : src/cv_airbrush_tool.c.s

src/cv_color_pick_tool.o: src/cv_color_pick_tool.c.o
.PHONY : src/cv_color_pick_tool.o

# target to build an object file
src/cv_color_pick_tool.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/cv_color_pick_tool.c.o
.PHONY : src/cv_color_pick_tool.c.o

src/cv_color_pick_tool.i: src/cv_color_pick_tool.c.i
.PHONY : src/cv_color_pick_tool.i

# target to preprocess a source file
src/cv_color_pick_tool.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/cv_color_pick_tool.c.i
.PHONY : src/cv_color_pick_tool.c.i

src/cv_color_pick_tool.s: src/cv_color_pick_tool.c.s
.PHONY : src/cv_color_pick_tool.s

# target to generate assembly for a file
src/cv_color_pick_tool.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/cv_color_pick_tool.c.s
.PHONY : src/cv_color_pick_tool.c.s

src/cv_curve_tool.o: src/cv_curve_tool.c.o
.PHONY : src/cv_curve_tool.o

# target to build an object file
src/cv_curve_tool.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/cv_curve_tool.c.o
.PHONY : src/cv_curve_tool.c.o

src/cv_curve_tool.i: src/cv_curve_tool.c.i
.PHONY : src/cv_curve_tool.i

# target to preprocess a source file
src/cv_curve_tool.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/cv_curve_tool.c.i
.PHONY : src/cv_curve_tool.c.i

src/cv_curve_tool.s: src/cv_curve_tool.c.s
.PHONY : src/cv_curve_tool.s

# target to generate assembly for a file
src/cv_curve_tool.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/cv_curve_tool.c.s
.PHONY : src/cv_curve_tool.c.s

src/cv_drawing.o: src/cv_drawing.c.o
.PHONY : src/cv_drawing.o

# target to build an object file
src/cv_drawing.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/cv_drawing.c.o
.PHONY : src/cv_drawing.c.o

src/cv_drawing.i: src/cv_drawing.c.i
.PHONY : src/cv_drawing.i

# target to preprocess a source file
src/cv_drawing.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/cv_drawing.c.i
.PHONY : src/cv_drawing.c.i

src/cv_drawing.s: src/cv_drawing.c.s
.PHONY : src/cv_drawing.s

# target to generate assembly for a file
src/cv_drawing.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/cv_drawing.c.s
.PHONY : src/cv_drawing.c.s

src/cv_ellipse_tool.o: src/cv_ellipse_tool.c.o
.PHONY : src/cv_ellipse_tool.o

# target to build an object file
src/cv_ellipse_tool.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/cv_ellipse_tool.c.o
.PHONY : src/cv_ellipse_tool.c.o

src/cv_ellipse_tool.i: src/cv_ellipse_tool.c.i
.PHONY : src/cv_ellipse_tool.i

# target to preprocess a source file
src/cv_ellipse_tool.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/cv_ellipse_tool.c.i
.PHONY : src/cv_ellipse_tool.c.i

src/cv_ellipse_tool.s: src/cv_ellipse_tool.c.s
.PHONY : src/cv_ellipse_tool.s

# target to generate assembly for a file
src/cv_ellipse_tool.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/cv_ellipse_tool.c.s
.PHONY : src/cv_ellipse_tool.c.s

src/cv_eraser_tool.o: src/cv_eraser_tool.c.o
.PHONY : src/cv_eraser_tool.o

# target to build an object file
src/cv_eraser_tool.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/cv_eraser_tool.c.o
.PHONY : src/cv_eraser_tool.c.o

src/cv_eraser_tool.i: src/cv_eraser_tool.c.i
.PHONY : src/cv_eraser_tool.i

# target to preprocess a source file
src/cv_eraser_tool.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/cv_eraser_tool.c.i
.PHONY : src/cv_eraser_tool.c.i

src/cv_eraser_tool.s: src/cv_eraser_tool.c.s
.PHONY : src/cv_eraser_tool.s

# target to generate assembly for a file
src/cv_eraser_tool.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/cv_eraser_tool.c.s
.PHONY : src/cv_eraser_tool.c.s

src/cv_flood_fill_tool.o: src/cv_flood_fill_tool.c.o
.PHONY : src/cv_flood_fill_tool.o

# target to build an object file
src/cv_flood_fill_tool.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/cv_flood_fill_tool.c.o
.PHONY : src/cv_flood_fill_tool.c.o

src/cv_flood_fill_tool.i: src/cv_flood_fill_tool.c.i
.PHONY : src/cv_flood_fill_tool.i

# target to preprocess a source file
src/cv_flood_fill_tool.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/cv_flood_fill_tool.c.i
.PHONY : src/cv_flood_fill_tool.c.i

src/cv_flood_fill_tool.s: src/cv_flood_fill_tool.c.s
.PHONY : src/cv_flood_fill_tool.s

# target to generate assembly for a file
src/cv_flood_fill_tool.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/cv_flood_fill_tool.c.s
.PHONY : src/cv_flood_fill_tool.c.s

src/cv_line_tool.o: src/cv_line_tool.c.o
.PHONY : src/cv_line_tool.o

# target to build an object file
src/cv_line_tool.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/cv_line_tool.c.o
.PHONY : src/cv_line_tool.c.o

src/cv_line_tool.i: src/cv_line_tool.c.i
.PHONY : src/cv_line_tool.i

# target to preprocess a source file
src/cv_line_tool.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/cv_line_tool.c.i
.PHONY : src/cv_line_tool.c.i

src/cv_line_tool.s: src/cv_line_tool.c.s
.PHONY : src/cv_line_tool.s

# target to generate assembly for a file
src/cv_line_tool.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/cv_line_tool.c.s
.PHONY : src/cv_line_tool.c.s

src/cv_paintbrush_tool.o: src/cv_paintbrush_tool.c.o
.PHONY : src/cv_paintbrush_tool.o

# target to build an object file
src/cv_paintbrush_tool.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/cv_paintbrush_tool.c.o
.PHONY : src/cv_paintbrush_tool.c.o

src/cv_paintbrush_tool.i: src/cv_paintbrush_tool.c.i
.PHONY : src/cv_paintbrush_tool.i

# target to preprocess a source file
src/cv_paintbrush_tool.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/cv_paintbrush_tool.c.i
.PHONY : src/cv_paintbrush_tool.c.i

src/cv_paintbrush_tool.s: src/cv_paintbrush_tool.c.s
.PHONY : src/cv_paintbrush_tool.s

# target to generate assembly for a file
src/cv_paintbrush_tool.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/cv_paintbrush_tool.c.s
.PHONY : src/cv_paintbrush_tool.c.s

src/cv_pencil_tool.o: src/cv_pencil_tool.c.o
.PHONY : src/cv_pencil_tool.o

# target to build an object file
src/cv_pencil_tool.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/cv_pencil_tool.c.o
.PHONY : src/cv_pencil_tool.c.o

src/cv_pencil_tool.i: src/cv_pencil_tool.c.i
.PHONY : src/cv_pencil_tool.i

# target to preprocess a source file
src/cv_pencil_tool.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/cv_pencil_tool.c.i
.PHONY : src/cv_pencil_tool.c.i

src/cv_pencil_tool.s: src/cv_pencil_tool.c.s
.PHONY : src/cv_pencil_tool.s

# target to generate assembly for a file
src/cv_pencil_tool.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/cv_pencil_tool.c.s
.PHONY : src/cv_pencil_tool.c.s

src/cv_polygon_tool.o: src/cv_polygon_tool.c.o
.PHONY : src/cv_polygon_tool.o

# target to build an object file
src/cv_polygon_tool.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/cv_polygon_tool.c.o
.PHONY : src/cv_polygon_tool.c.o

src/cv_polygon_tool.i: src/cv_polygon_tool.c.i
.PHONY : src/cv_polygon_tool.i

# target to preprocess a source file
src/cv_polygon_tool.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/cv_polygon_tool.c.i
.PHONY : src/cv_polygon_tool.c.i

src/cv_polygon_tool.s: src/cv_polygon_tool.c.s
.PHONY : src/cv_polygon_tool.s

# target to generate assembly for a file
src/cv_polygon_tool.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/cv_polygon_tool.c.s
.PHONY : src/cv_polygon_tool.c.s

src/cv_rect_select.o: src/cv_rect_select.c.o
.PHONY : src/cv_rect_select.o

# target to build an object file
src/cv_rect_select.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/cv_rect_select.c.o
.PHONY : src/cv_rect_select.c.o

src/cv_rect_select.i: src/cv_rect_select.c.i
.PHONY : src/cv_rect_select.i

# target to preprocess a source file
src/cv_rect_select.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/cv_rect_select.c.i
.PHONY : src/cv_rect_select.c.i

src/cv_rect_select.s: src/cv_rect_select.c.s
.PHONY : src/cv_rect_select.s

# target to generate assembly for a file
src/cv_rect_select.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/cv_rect_select.c.s
.PHONY : src/cv_rect_select.c.s

src/cv_rectangle_tool.o: src/cv_rectangle_tool.c.o
.PHONY : src/cv_rectangle_tool.o

# target to build an object file
src/cv_rectangle_tool.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/cv_rectangle_tool.c.o
.PHONY : src/cv_rectangle_tool.c.o

src/cv_rectangle_tool.i: src/cv_rectangle_tool.c.i
.PHONY : src/cv_rectangle_tool.i

# target to preprocess a source file
src/cv_rectangle_tool.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/cv_rectangle_tool.c.i
.PHONY : src/cv_rectangle_tool.c.i

src/cv_rectangle_tool.s: src/cv_rectangle_tool.c.s
.PHONY : src/cv_rectangle_tool.s

# target to generate assembly for a file
src/cv_rectangle_tool.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/cv_rectangle_tool.c.s
.PHONY : src/cv_rectangle_tool.c.s

src/cv_resize.o: src/cv_resize.c.o
.PHONY : src/cv_resize.o

# target to build an object file
src/cv_resize.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/cv_resize.c.o
.PHONY : src/cv_resize.c.o

src/cv_resize.i: src/cv_resize.c.i
.PHONY : src/cv_resize.i

# target to preprocess a source file
src/cv_resize.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/cv_resize.c.i
.PHONY : src/cv_resize.c.i

src/cv_resize.s: src/cv_resize.c.s
.PHONY : src/cv_resize.s

# target to generate assembly for a file
src/cv_resize.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/cv_resize.c.s
.PHONY : src/cv_resize.c.s

src/cv_rounded_rectangle_tool.o: src/cv_rounded_rectangle_tool.c.o
.PHONY : src/cv_rounded_rectangle_tool.o

# target to build an object file
src/cv_rounded_rectangle_tool.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/cv_rounded_rectangle_tool.c.o
.PHONY : src/cv_rounded_rectangle_tool.c.o

src/cv_rounded_rectangle_tool.i: src/cv_rounded_rectangle_tool.c.i
.PHONY : src/cv_rounded_rectangle_tool.i

# target to preprocess a source file
src/cv_rounded_rectangle_tool.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/cv_rounded_rectangle_tool.c.i
.PHONY : src/cv_rounded_rectangle_tool.c.i

src/cv_rounded_rectangle_tool.s: src/cv_rounded_rectangle_tool.c.s
.PHONY : src/cv_rounded_rectangle_tool.s

# target to generate assembly for a file
src/cv_rounded_rectangle_tool.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/cv_rounded_rectangle_tool.c.s
.PHONY : src/cv_rounded_rectangle_tool.c.s

src/file.o: src/file.c.o
.PHONY : src/file.o

# target to build an object file
src/file.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/file.c.o
.PHONY : src/file.c.o

src/file.i: src/file.c.i
.PHONY : src/file.i

# target to preprocess a source file
src/file.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/file.c.i
.PHONY : src/file.c.i

src/file.s: src/file.c.s
.PHONY : src/file.s

# target to generate assembly for a file
src/file.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/file.c.s
.PHONY : src/file.c.s

src/gp-image.o: src/gp-image.c.o
.PHONY : src/gp-image.o

# target to build an object file
src/gp-image.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/gp-image.c.o
.PHONY : src/gp-image.c.o

src/gp-image.i: src/gp-image.c.i
.PHONY : src/gp-image.i

# target to preprocess a source file
src/gp-image.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/gp-image.c.i
.PHONY : src/gp-image.c.i

src/gp-image.s: src/gp-image.c.s
.PHONY : src/gp-image.s

# target to generate assembly for a file
src/gp-image.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/gp-image.c.s
.PHONY : src/gp-image.c.s

src/gp_point_array.o: src/gp_point_array.c.o
.PHONY : src/gp_point_array.o

# target to build an object file
src/gp_point_array.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/gp_point_array.c.o
.PHONY : src/gp_point_array.c.o

src/gp_point_array.i: src/gp_point_array.c.i
.PHONY : src/gp_point_array.i

# target to preprocess a source file
src/gp_point_array.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/gp_point_array.c.i
.PHONY : src/gp_point_array.c.i

src/gp_point_array.s: src/gp_point_array.c.s
.PHONY : src/gp_point_array.s

# target to generate assembly for a file
src/gp_point_array.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/gp_point_array.c.s
.PHONY : src/gp_point_array.c.s

src/image_menu.o: src/image_menu.c.o
.PHONY : src/image_menu.o

# target to build an object file
src/image_menu.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/image_menu.c.o
.PHONY : src/image_menu.c.o

src/image_menu.i: src/image_menu.c.i
.PHONY : src/image_menu.i

# target to preprocess a source file
src/image_menu.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/image_menu.c.i
.PHONY : src/image_menu.c.i

src/image_menu.s: src/image_menu.c.s
.PHONY : src/image_menu.s

# target to generate assembly for a file
src/image_menu.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/image_menu.c.s
.PHONY : src/image_menu.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/main.c.s
.PHONY : src/main.c.s

src/pixbuf-file-chooser.o: src/pixbuf-file-chooser.c.o
.PHONY : src/pixbuf-file-chooser.o

# target to build an object file
src/pixbuf-file-chooser.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/pixbuf-file-chooser.c.o
.PHONY : src/pixbuf-file-chooser.c.o

src/pixbuf-file-chooser.i: src/pixbuf-file-chooser.c.i
.PHONY : src/pixbuf-file-chooser.i

# target to preprocess a source file
src/pixbuf-file-chooser.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/pixbuf-file-chooser.c.i
.PHONY : src/pixbuf-file-chooser.c.i

src/pixbuf-file-chooser.s: src/pixbuf-file-chooser.c.s
.PHONY : src/pixbuf-file-chooser.s

# target to generate assembly for a file
src/pixbuf-file-chooser.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/pixbuf-file-chooser.c.s
.PHONY : src/pixbuf-file-chooser.c.s

src/pixbuf_util.o: src/pixbuf_util.c.o
.PHONY : src/pixbuf_util.o

# target to build an object file
src/pixbuf_util.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/pixbuf_util.c.o
.PHONY : src/pixbuf_util.c.o

src/pixbuf_util.i: src/pixbuf_util.c.i
.PHONY : src/pixbuf_util.i

# target to preprocess a source file
src/pixbuf_util.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/pixbuf_util.c.i
.PHONY : src/pixbuf_util.c.i

src/pixbuf_util.s: src/pixbuf_util.c.s
.PHONY : src/pixbuf_util.s

# target to generate assembly for a file
src/pixbuf_util.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/pixbuf_util.c.s
.PHONY : src/pixbuf_util.c.s

src/selection.o: src/selection.c.o
.PHONY : src/selection.o

# target to build an object file
src/selection.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/selection.c.o
.PHONY : src/selection.c.o

src/selection.i: src/selection.c.i
.PHONY : src/selection.i

# target to preprocess a source file
src/selection.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/selection.c.i
.PHONY : src/selection.c.i

src/selection.s: src/selection.c.s
.PHONY : src/selection.s

# target to generate assembly for a file
src/selection.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/selection.c.s
.PHONY : src/selection.c.s

src/toolbar.o: src/toolbar.c.o
.PHONY : src/toolbar.o

# target to build an object file
src/toolbar.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/toolbar.c.o
.PHONY : src/toolbar.c.o

src/toolbar.i: src/toolbar.c.i
.PHONY : src/toolbar.i

# target to preprocess a source file
src/toolbar.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/toolbar.c.i
.PHONY : src/toolbar.c.i

src/toolbar.s: src/toolbar.c.s
.PHONY : src/toolbar.s

# target to generate assembly for a file
src/toolbar.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/toolbar.c.s
.PHONY : src/toolbar.c.s

src/undo.o: src/undo.c.o
.PHONY : src/undo.o

# target to build an object file
src/undo.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/undo.c.o
.PHONY : src/undo.c.o

src/undo.i: src/undo.c.i
.PHONY : src/undo.i

# target to preprocess a source file
src/undo.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/undo.c.i
.PHONY : src/undo.c.i

src/undo.s: src/undo.c.s
.PHONY : src/undo.s

# target to generate assembly for a file
src/undo.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mate-paint.dir/build.make CMakeFiles/mate-paint.dir/src/undo.c.s
.PHONY : src/undo.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... mate-paint"
	@echo "... src/clipboard.o"
	@echo "... src/clipboard.i"
	@echo "... src/clipboard.s"
	@echo "... src/color-picker.o"
	@echo "... src/color-picker.i"
	@echo "... src/color-picker.s"
	@echo "... src/color.o"
	@echo "... src/color.i"
	@echo "... src/color.s"
	@echo "... src/cv_airbrush_tool.o"
	@echo "... src/cv_airbrush_tool.i"
	@echo "... src/cv_airbrush_tool.s"
	@echo "... src/cv_color_pick_tool.o"
	@echo "... src/cv_color_pick_tool.i"
	@echo "... src/cv_color_pick_tool.s"
	@echo "... src/cv_curve_tool.o"
	@echo "... src/cv_curve_tool.i"
	@echo "... src/cv_curve_tool.s"
	@echo "... src/cv_drawing.o"
	@echo "... src/cv_drawing.i"
	@echo "... src/cv_drawing.s"
	@echo "... src/cv_ellipse_tool.o"
	@echo "... src/cv_ellipse_tool.i"
	@echo "... src/cv_ellipse_tool.s"
	@echo "... src/cv_eraser_tool.o"
	@echo "... src/cv_eraser_tool.i"
	@echo "... src/cv_eraser_tool.s"
	@echo "... src/cv_flood_fill_tool.o"
	@echo "... src/cv_flood_fill_tool.i"
	@echo "... src/cv_flood_fill_tool.s"
	@echo "... src/cv_line_tool.o"
	@echo "... src/cv_line_tool.i"
	@echo "... src/cv_line_tool.s"
	@echo "... src/cv_paintbrush_tool.o"
	@echo "... src/cv_paintbrush_tool.i"
	@echo "... src/cv_paintbrush_tool.s"
	@echo "... src/cv_pencil_tool.o"
	@echo "... src/cv_pencil_tool.i"
	@echo "... src/cv_pencil_tool.s"
	@echo "... src/cv_polygon_tool.o"
	@echo "... src/cv_polygon_tool.i"
	@echo "... src/cv_polygon_tool.s"
	@echo "... src/cv_rect_select.o"
	@echo "... src/cv_rect_select.i"
	@echo "... src/cv_rect_select.s"
	@echo "... src/cv_rectangle_tool.o"
	@echo "... src/cv_rectangle_tool.i"
	@echo "... src/cv_rectangle_tool.s"
	@echo "... src/cv_resize.o"
	@echo "... src/cv_resize.i"
	@echo "... src/cv_resize.s"
	@echo "... src/cv_rounded_rectangle_tool.o"
	@echo "... src/cv_rounded_rectangle_tool.i"
	@echo "... src/cv_rounded_rectangle_tool.s"
	@echo "... src/file.o"
	@echo "... src/file.i"
	@echo "... src/file.s"
	@echo "... src/gp-image.o"
	@echo "... src/gp-image.i"
	@echo "... src/gp-image.s"
	@echo "... src/gp_point_array.o"
	@echo "... src/gp_point_array.i"
	@echo "... src/gp_point_array.s"
	@echo "... src/image_menu.o"
	@echo "... src/image_menu.i"
	@echo "... src/image_menu.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/pixbuf-file-chooser.o"
	@echo "... src/pixbuf-file-chooser.i"
	@echo "... src/pixbuf-file-chooser.s"
	@echo "... src/pixbuf_util.o"
	@echo "... src/pixbuf_util.i"
	@echo "... src/pixbuf_util.s"
	@echo "... src/selection.o"
	@echo "... src/selection.i"
	@echo "... src/selection.s"
	@echo "... src/toolbar.o"
	@echo "... src/toolbar.i"
	@echo "... src/toolbar.s"
	@echo "... src/undo.o"
	@echo "... src/undo.i"
	@echo "... src/undo.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system
